#!/usr/bin/env python3
"""Regenerate the vendored i18n maps for cron-utils-web.

Reads the 18 CronUtilsI18N*.properties files shipped with
cron-utils-descriptor and emits
cron-utils-web/src/main/java/com/cronutils/web/EmbeddedBundleData.java,
a pure-data holder (one unmodifiable map per locale suffix, ASCII-only
\\u escapes). Strings are vendored verbatim; never hand-edit the output.

TeaVM WASM-GC cannot resolve ResourceBundle.getBundle at runtime
("Bundle not found"), so the web module serves these maps through an
in-memory ResourceBundle instead. Per-key fallback to the base (English)
map mirrors the JVM ResourceBundle parent chain, including upstream's
partial translations.

Usage (repo root):
    python3 scripts/gen-web-bundles.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "cron-utils-descriptor/src/main/resources/com/cronutils"
OUT = ROOT / "cron-utils-web/src/main/java/com/cronutils/web/EmbeddedBundleData.java"


def parse_properties(path):
    props = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.lstrip(" \t\f")
        if not line or line.startswith("#") or line.startswith("!"):
            continue
        m = re.split(r"(?<!\\)[=:]", line, maxsplit=1)
        if len(m) == 1:
            key, value = m[0].strip(), ""
        else:
            key, value = m[0].strip(), m[1].lstrip(" \t\f")
        key = decode_escapes(key.strip())
        props[key] = decode_escapes(value)
    return props


def decode_escapes(s):
    out = []
    i = 0
    simple = {"t": "\t", "n": "\n", "r": "\r", "f": "\f", "\\": "\\"}
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            nxt = s[i + 1]
            if nxt == "u":
                out.append(chr(int(s[i + 2:i + 6], 16)))
                i += 6
                continue
            out.append(simple.get(nxt, nxt))
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def java_escape(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif o < 32 or o > 126:
            out.append("\\u%04x" % o)
        else:
            out.append(ch)
    return "".join(out)


def main():
    files = sorted(SRC.glob("CronUtilsI18N*.properties"))
    if len(files) != 18:
        sys.exit("expected 18 bundle files, found %d" % len(files))
    locales = {}
    for path in files:
        m = re.fullmatch(r"CronUtilsI18N(?:_([a-z]+))?\.properties", path.name)
        locales[m.group(1) or "base"] = parse_properties(path)

    parts = [
        "package com.cronutils.web;",
        "",
        "import java.util.Collections;",
        "import java.util.HashMap;",
        "import java.util.Map;",
        "",
        "/**",
        " * Vendored cron-utils descriptor strings, generated by",
        " * {@code python3 scripts/gen-web-bundles.py} from the",
        " * {@code CronUtilsI18N*.properties} resources. DO NOT EDIT.",
        " */",
        "final class EmbeddedBundleData {",
        "",
        "    private static final Map<String, Map<String, String>> BY_LANGUAGE = new HashMap<>();",
        "    private static final Map<String, String> BASE = new HashMap<>();",
        "",
        "    static {",
    ]
    base = locales.pop("base")
    for key in sorted(base):
        parts.append('        BASE.put("%s", "%s");' % (java_escape(key), java_escape(base[key])))
    for lang in sorted(locales):
        var = "M_" + lang.upper()
        parts.append("        Map<String, String> %s = new HashMap<>();" % var)
        for key in sorted(locales[lang]):
            parts.append('        %s.put("%s", "%s");' % (var, java_escape(key), java_escape(locales[lang][key])))
        parts.append('        BY_LANGUAGE.put("%s", Collections.unmodifiableMap(%s));' % (lang, var))
    parts += [
        "    }",
        "",
        "    private EmbeddedBundleData() {",
        "    }",
        "",
        "    static Map<String, String> base() {",
        "        return Collections.unmodifiableMap(BASE);",
        "    }",
        "",
        "    static Map<String, String> forLanguage(String language) {",
        '        return BY_LANGUAGE.get(language == null ? "" : language);',
        "    }",
        "}",
        "",
    ]
    OUT.write_text("\n".join(parts), encoding="ascii")
    total = sum(len(v) for v in locales.values()) + len(base)
    print("wrote %s (%d locales, %d entries)" % (OUT, len(locales) + 1, total))


if __name__ == "__main__":
    main()
